### ISSUE TITLE
Totally F*ckin awesome language u got there :) 

### ISSUE THREAD

**Issue by kristianmandrup** [ckknight/gorillascript#1]
Just one note. How about property listeners? I have recently been looking into EmberJS where they have property bindings, so that you can have properties and methods with value caching behaviour automatically update then other properties change, in effect resulting in a chain reaction, so that an update in the data store automatically can update controllers and views with the new state (similar to Meteor.js). Would be so awesome if this was supported natively in a language ;)

**Comment by ckknight** [comment]
I'm willing to work with you for ideas on how to do such a thing. First, one needs to come up with a good language-level API that fits in well, then writing up some test cases, and actual implementation should be definitely doable.
