### ISSUE TITLE
Allow macros to access a compact string representation of the input expressions

### ISSUE THREAD

**Issue by andreyvit** [ckknight/gorillascript#108]
Here's what I'm trying to do:

```
macro assert-equals(x, y)
  let ast-node-to-string(node) node.inspect().replace(r'\s+'g, '')
  let xstr = ast-node-to-string(x)
  let ystr = ast-node-to-string(y)
  @maybe-cache x, #(set-x, x)
    @maybe-cache y, #(set-y, y)
      AST
        if $set-x != $set-y
          throw new Error("assert-equals failed, " & $xstr & " != " & $ystr & ": " & JSON.stringify($x, null, 2) & " != " & JSON.stringify($y, null, 2))
```

It would be nice to have a better way to implement `ast-node-to-string` (and to share it between macros, which I think is covered by #91).

Right now the generated code is something like:

```
throw new Error('assert-deep-equals failed, Symbol.ident("result") != Call(Symbol.array,Value(12),Value(17),Value(20)): ' + __str(JSON.stringify(result, null, 2)) + " != " + __str(JSON.stringify(_ref, null, 2)));
```

while I would like to get:

```
throw new Error('assert-deep-equals failed, result != [12, 17, 20]: ' + __str(JSON.stringify(result, null, 2)) + " != " + __str(JSON.stringify(_ref, null, 2)));
```

I don't think there's an AST method that returns the original source representation currently, right?

P.S. Why the hell does the second maybe-cache call work, btw? `this` should have been reset by the second callback (which I'd like to see fixed once and for all in #107, but right now it's unexplainable).

**Comment by ckknight** [comment]
Hmm, yeah, I could just make their `.toString()` (not the `.inspect()`) a terse representation.

Regarding your P.S.: @maybe-cache does callback@ this, ...etc, so the `this` is kept the same kinda by cheating.
