### ISSUE TITLE
need a forum or group to discuss stuff

### ISSUE THREAD

**Issue by prodev42** [ckknight/gorillascript#113]
hi can we get a forum or group to discuss gorillascript plz.

**Comment by andreyvit** [comment]
I don't know @ckknight's plans for GorillaScript, but in CoffeeScript discussions tend to happen on GitHub (you can ‘watch’ this repository to follow them) and on IRC.

**Comment by prodev42** [comment]
you mean i can ask my question like an issue here?

**Comment by andreyvit** [comment]
In the absence of official guidance to the contrary, I'd say why not. If something isn't clear, it can be thought of as a documentation bug. :-)

**Comment by prodev42** [comment]
in the documentation it says in Javascript:

```
[] + [] === ""
{} + {} === "[object Object][object Object]"
true + [] === "true"
```

so I tried the following in GS:

```
print [] ~+ [] ~= "" 
print {} ~+ {} ~= "[object Object][object Object]"
print true ~+ [] ~= "true"
```

Now only the first statement returned true, how do I get the 2nd and 3rd to return true just like in Javascript?

**Comment by ckknight** [comment]
Well, what do they return for you that they are different?

**Comment by prodev42** [comment]
print {} ~+ {} ~= "[object Object][object Object]" returned false
print true ~+ [] ~= "true" returned false

**Comment by ckknight** [comment]
oh, you're using `~+`, not `~&`. So you're forcing numeric addition rather than string concatenation (which is what you're sort of copying from the JavaScript example, I assume).

**Comment by prodev42** [comment]
Awesome...~& worked... 

I am trying to:

```
print __VERSION__  
```

but it just show a blank line from the interpreter is that normal?
