### ISSUE TITLE
Destroy immediately this project

### ISSUE THREAD

**Issue by yuchi** [ckknight/gorillascript#120]
Since I the discovery of Gorilla Script I've not been able to work on my usual projects. It's been more than 3 days that I can't help myself from designing custom preludes for my environment. I've re-implemented "require!" in a lot of different ways, I'm now trying to design an Haskell-like type system with data declarations... Please! Stop this madness! It's in my ears, it's in my mind! Take it out!

---

Thank you, when I read `jsPrelude.gs` I was literally (literally literally) moved.

**Comment by ckknight** [comment]
I'm sorry you were literally moved. That does sound like a bug. How many meters do you think you went?

**Comment by yuchi** [comment]
A centimeter every macro i read. It was in a random direction each time, so luckily it was pretty balanced and I could keep reading. That was fun!

Really, I didn't expect that counter-pun! :)

Go on with this awesome work, please!
