### ISSUE TITLE
Use of 'let' for immutable assigns in assign-macros

### ISSUE THREAD

**Issue by goldfeld** [ckknight/gorillascript#134]
I'm trying to do `let my-array []= maybe-array`
With the macro definition below:

```
macro operator assign []=
  @maybe-cache-assign right, #(set-right, right)
    ASTE $left = if $set-right? then (if is-array! $right then $right else [$right]) else []
```

But the macro expects me to use the `:=` syntax instead.

**Comment by ckknight** [comment]
Eh, sorry, the use of certain tokens like `[`, `]`, `(`, `)`, `{`, `}` can't be used as macro names due to their meaning as fundamental building blocks of gorillascript.

Also, `let` only works with `=`. Assign macros are to be used on mutable, previously-declared bindings.

**Comment by ckknight** [comment]
And actually, in your case, you should have used `$left := ...`, as `$left = ...` isn't valid syntax in GorillaScript, as specific macros such as `let` or function parameters use `=` as a token.

**Comment by goldfeld** [comment]
Thanks, I understand I should have used `:=` and have previously declared the variable as mutable so as to make it work. On further thinking I guess it's a good compromise for composability that I instead use a `to-array!` macro and assign it's invocation.
