### ISSUE TITLE
Document site rework.

### ISSUE THREAD

**Issue by unc0** [ckknight/gorillascript#15]
http://unc0.github.io/gorillascript/
- flow layout, _easier to read in split 50/50 1980x1060 screen_
- readability
- add syntax highlight
- toc is easier to navigate
- run code in "try it out", _default `alert` statment isn't work, using `console.log` will run_

**Comment by ckknight** [comment]
Ooh, very nice. I like it.

**Comment by ckknight** [comment]
Mind making a pull request?

**Comment by unc0** [comment]
There still some problem in gorillascript syntax highlight, you may check out those horrible regex in prism_gs.js first. Is it possilbe to use gorilla AST output to highlight gorilla code?

**Comment by unc0** [comment]
`prism.gs` need compile to js first, or highlighting for gorilla will fail.
