### ISSUE TITLE
try/catch generator state mismatch

### ISSUE THREAD

**Issue by kkirby** [ckknight/gorillascript#158]
If you have a promise generator like so:

```
promise!
    try
        yield @doSomethingAsync()
    catch e
        console.error e
    doSomething()
```

And if `@doSomethingAsync()` rejects, then the `throw` clause is hit, but the internal state is set to `2` and not `0`, which is what the `throw` statement expects:

```
function _step(_received) {
    while (true) {
        switch (_state) {
            case 0:
                // State is being set to 2
                _state = 2;
                return {
                    done: false,
                    value: _this._sync()
                };
            case 1:
                console.error(e);
                ++_state;
            case 2:
                ++_state;
                return {
                    done: true,
                    value: doSomething()
                };
            case 3:
                return {
                    done: true,
                    value: void 0
                };
            default:
                throw new Error("Unknown state: " + _state);
        }
    }
}

function _throw(_e) {
    // State is being checked if is 0. But will be 2 instead.
    if (_state === 0) {
        e = _e;
        _state = 1;
    } else {
        _close();
        throw _e;
    }
}
```

It works fine if there is no leading `doSomething()` after the `try/catch`, or if you assign the value of the yield to a variable.

**Comment by unc0** [comment]
I've tried use gorillascript's promise to build a HTML5 powerd outline editor, promise is really hard to use. With ES6 generator, you can try [thunks](https://github.com/thunks/thunks) . I'm using [highland](http://highlandjs.org/) in my web scrapper project, it's way better than promise. These two library can handle error properly.

**Comment by kkirby** [comment]
This has been fixed in my [community repo](https://github.com/kkirby/gorillascript)
