### ISSUE TITLE
Great!

### ISSUE THREAD

**Issue by luciotato** [ckknight/gorillascript#2]
Great! Great!
and very well presented, going from simple to complex in a nice gradual curve.

Question:
How long have you been working on this?

Warning:
google search for "gorillascript" render an unrelated "gorrilascript" from Mar 13, 2007
you may consider renaming the language... (ref: the Firefox history)

Feature suggestions:
1) "try-catch-else"

a) Constructive criticism: 
    is "else" really necessary in "try-catch-else"

what's the difference between:
-the example:-
try
  something-dangerous()
catch e as SpecificError
  handle-error(e)
catch e
  uh-oh()
else
  whew()
finally
  cleanup()

...and...

try
  something-dangerous()
  whew()
catch e as SpecificError
  handle-error(e)
catch e
  uh-oh()
finally
  cleanup()

b) Alternatives: 
IMO try-catch it is not an elegant construction for exceptions. How about using the PL-like form?
It's a more elegant case-when structure.

function foo()
    something-dangerous()
    whew()

exceptions // "as e" by default
    when SpecificError  
        handle-error(e)
    when others
        uh-oh()
finally
    cleanup()

...and keeping "try" as a synonym for Pl's "begin", as in:

function foo()
    something-safe()
    something-else-safe()
    try
        something-dangerous()
    exceptions
        when SpecificError
            handle-error(e)
        when others
            uh-oh()

```
whew()
the-next-safe-thing()
```

2) Changed operators - (Strict vs unstrict equality)

> > Many of the operators have changed to provide more clarity or to free up the usage of certain >>symbols.

  === - ==
  !== - !=
  == - ~=
  != - !~=

Constructive criticism: This change will make very hard to migrate pure js to gorilla (leading to subtle behavior changes if pasting js on a .gs file ). 

Suggestion:
since you're not using "=" for assignment, how about the following:

 === - =  // shorter
 !== - not =  // easier to read 
 == - ==  //unchanged, to ease migration, and mind-switching from js to gorilla and back
 != - !=   //unchanged, -idem-

**Comment by ckknight** [comment]
Been working on this for several months now.

try-catch-else already exists. The else block runs only if an error wasn't caught.

basically,

```
try
  alpha()
catch e as MyError
  bravo()
catch e
  charlie()
else
  delta()
finally
  echo()
```

Is functionally equivalent to the following:

```
try
  let mutable _else = true
  try
    alpha()
  catch e
    _else := false
    if e instanceof MyError
      bravo()
    else
      charlie()
  finally
    if _else
      delta()
finally
  echo()
```

I'm not sure I'm too fond of your `exceptions` syntax, though it is similar to Ruby's blocks that can have any `rescue`/`ensure` on them, I don't think having an explicit `try` block is a bad thing.

I admit that the `==`/`!=` changes are different from JavaScript, but there is no good reason in the general case to use the unstrict version (regular `==` in JS or `~=` in GS) except when comparing to null, which already has a special operator `?`.

`=` is used in some places, particularly in macros such as `let` or setting default parameter values, so I wouldn't want to overload that operator, even though it could be done.

With regards to the language name: at this point, I don't have any plans to rename, as I'm pretty comfortable with GorillaScript. I'm disappointed in myself that I didn't catch the other project before I decided, but hopefully it doesn't become an issue.

**Comment by unc0** [comment]
> = is used in some places, particularly in macros such as let or setting default parameter values, so I wouldn't want to overload that operator, even though it could be done.

I tried some goriilascript today, I don't know why GS need `:=` , isn't `let foo = 'bar'` and `foo = 'bar'` looks different already? I think params default value should use `:=` :

```
let mutable foo = #(bar = 'baz') ->
// vs
let mutable foo = #(bar := 'baz') ->
```

What if `def(ine)` means immutable, and `let` means mutable:

```
def a = [10, 20]
let b = #(x := 10)
  def b = 30
  b = x + b
def c(x) -> x
```

**Comment by ckknight** [comment]
There's `let` and `let mutable` for a reason. Requesting something to be mutable should be more of a chore than not.

Also, `def` already means "assign this to the current context's object" as in classes or enums.

Having `mutable` be separate also allows for such things as:

```
let [a, mutable b] = f()
a += 1 // error
b += 1 // perfectly fine
```

Changing a mutable object is "meant" to look a bit different than declaration, thus the difference between `=` meaning "here is the value at declaration time" and `:=` meaning "reassign the (obviously mutable) left value to the right".

So, no, GorillaScript doesn't "need" a separate `:=` operator, but it's there on purpose for design reasons.

**Comment by ckknight** [comment]
With regards to the parameters, `=` effectively means `?=`, though the latter doesn't work in the parameter. If I do get that to work, then I could also get other operators such as `#(x or= 0)` or `#(x and= 0)`, with `#(x = 0)` being functionally equivalent to `#(x ?= 0)`

**Comment by unc0** [comment]
> With regards to the parameters, = effectively means ?=, though the latter doesn't work in the parameter. If I do get that to work, then I could also get other operators such as #(x or= 0) or #(x and= 0), with #(x = 0) being functionally equivalent to #(x ?= 0)

Maybe not use `=` in parameters default, only use `or= and= ?=`, so `:=` only means reassign mutable variable?

**Comment by ckknight** [comment]
Well, `:=` only means reassignment of a mutable variable or a member (e.g. `obj[key]`) already. I don't really see the harm in having the default parameter value use `=` as the token.
