### ISSUE TITLE
Use a better test system

### ISSUE THREAD

**Issue by ckknight** [ckknight/gorillascript#22]
The test suite would probably be better suited to using [mocha](https://github.com/visionmedia/mocha) or something similar rather than the custom-rolled one that's currently in use.

**Comment by unc0** [comment]
[Chai](http://chaijs.com/) + mocha is quite good.

**Comment by ckknight** [comment]
Fixed in 7ccde73ba6d1a0b344efa58fa625962a43cb6578, using mocha, chai, and sinon.

Also can do gork test:promise, which runs the Promises/A+ spec tests.
