### ISSUE TITLE
Table of contents link doesn't work on iPad

### ISSUE THREAD

**Issue by ckknight** [ckknight/gorillascript#24]
In the gh-pages branch, if you visit the site, the "Table of contents" link normally on the top-right is simply not there.

**Comment by unc0** [comment]
I didn't test on mobile device, I don't have an iPad, so I just tested on an android tablet, opera will show that "button" but it doesn't support scrolling the TOC long list, android 4 vanilla browser also doesn't show that "button", but if you click around _that_ area, it will come up and it is in the right position, the TOC list scrolls fine.

**Comment by ckknight** [comment]
I'm working on it now, it's just a matter of replacing hover events when touch is detected.
