### ISSUE TITLE
Inaccuracy in Docs

### ISSUE THREAD

**Issue by rtfeldman** [ckknight/gorillascript#40]
GS looks like a nice language!

The "Immutable by default" section should really more accurately be titled "Constant by default". As noted in the body of that section, "The object in the value can still be mutated (assuming it is mutable)" - in other words, what's guaranteed is that the reference won't change, not that the value itself is immutable.

This may sound like a nit pick, but the heading gave me the wrong impression until I read the fine print; I took "immutability by default" to mean the same thing as it does in other altJS languages like ClojureScript, Roy, and Elm, namely that the objects themselves are immutable.

**Comment by ckknight** [comment]
Immutable in that case means that variables and scope is immutable by default, which is in line with the terminology of the ES6 specifications.

I can see how it can be confusing, which is why I tried to clarify. I'll probably go back and try to make the docs more clear, though.
