### ISSUE TITLE
Grunt support

### ISSUE THREAD

**Issue by ckknight** [ckknight/gorillascript#75]
There should be a grunt task on npm to facilitate compiling gorillascript files.

**Comment by unc0** [comment]
I've mod grunt-coffee to grunt-gorilla like 60%, the sourcemap issue need fix.

**Comment by ckknight** [comment]
unc0, I've come up with a very nice solution on my end that I'm about to publish.

**Comment by ckknight** [comment]
Shoot, I put the wrong issue number in that commit.

**Comment by ckknight** [comment]
https://github.com/ckknight/grunt-gorillascript

**Comment by unc0** [comment]
Cool, I didn't think of that.
