### ISSUE TITLE
Generate JSCoverage compatible instrumented sourcecode for testing code coverage with mocha.

### ISSUE THREAD

**Issue by unc0** [ckknight/gorillascript#78]
Gorillascript may generate some __functions to support some language features, if we are using jscoverage/blanket modules to instrument generated js code, those __functions will unlikely to be covered by tests. Coffeescript got [coffee-coverage](https://npmjs.org/package/coffee-coverage) to support jscoverage comatible instrument. 

https://github.com/benbria/coffee-coverage/wiki/Design

**Comment by ckknight** [comment]
Hmm, I think I can do this by adding a way to pipe the final JavaScript AST into a function provided which would, in turn, produce another JavaScript AST, which would then be compiled, potentially still with full SourceMap support.
