### ISSUE TITLE
process.argv

### ISSUE THREAD

**Issue by unc0** [ckknight/gorillascript#81]
you should test `gorilla x.gs a b c` before closing #59.

**Comment by ckknight** [comment]
I did. What operating system and shell are you running?

**Comment by ckknight** [comment]
Upon further review, you were right. I'm adding automated tests for the CLI now.

**Comment by ckknight** [comment]
Assuming `script.gs` has the following code:

```
#!/usr/bin/env gorilla
console.log process.argv
```

`./script.gs alpha bravo` => `["gorilla", fs.realpathSync("./script.gs"), "alpha", "bravo"]`
`gorilla script.gs alpha bravo` => `["gorilla", fs.realpathSync("./script.gs"), "alpha", "bravo"]`

And after compiling:

`./script.js alpha bravo` => `["node", fs.realpathSync("./script.js"), "alpha", "bravo"]`
`node script.js alpha bravo` => `["node", fs.realpathSync("./script.js"), "alpha", "bravo"]`
